### ISSUE TITLE
Exception thrown at IsInterstitialReady Unity 5.9

### ISSUE THREAD

**Issue by kkarunakaran** [mopub/mopub-unity-sdk#90]
When MoPub.IsInterstitialReady is called from Unity, a java exception is thrown

#### Steps to reproduce the behavior:
- Launch the app
- Once SDK is initialized, check if any ad is cached by calling the function MoPub.IsInterstitialReady

#### Expected behavior:
No progression block or crash

#### Observed behavior:
App crashes

#### Evidence:
Device log files, Network log file, etc.

> AndroidJavaException: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.mopub.mobileads.MoPubInterstitial.isReady()' on a null object reference
> java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.mopub.mobileads.MoPubInterstitial.isReady()' on a null object reference        
> at com.mopub.unity.MoPubInterstitialUnityPlugin.isReady(MoPubInterstitialUnityPlugin.java:65)    
> at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
> at com.unity3d.player.UnityPlayer.c(Unknown Source:0)      
> at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)      
> at android.os.MessageQueue.next(MessageQueue.java:394)        
> at android.os.Looper.loop(Looper.java:142)       
> at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)      
> at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0       
> at UnityEngine.AndroidJNISafe.CallBooleanMethod (IntPtr obj, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0

**Comment by sdolim** [comment]
It appears that the Java code expects to only call IsInterstitialReady after a call to RequestInterstialAd, which is the function that allocates the object that is missing here.  It's a legitimate bug, but you can work around it in the meantime by making sure you call Ready only after Request.

**Comment by aornelas** [comment]
Thanks for your report! We have fixed this on release [5.10.0](https://github.com/mopub/mopub-unity-sdk/releases/tag/v5.10.0).

**Comment by SebaDudzic** [comment]
Hi. I have exactly the same problem, and I'm using 5.10.0. Are you sure this fix was shipped?

`AndroidJavaException: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.mopub.mobileads.MoPubInterstitial.isReady()' on a null object reference`

**Comment by karthikk0424** [comment]
The issue is not fixed yet in the aar even on 5.10 release. If you unpack the aar and check the code there is no null guard.

**Comment by SebaDudzic** [comment]
@aornelas please reopen this issue, and provide us a fix in next release

**Comment by chauduyphanvu** [comment]
@SebaDudzic, could you share with us the C# code you are calling that throws that Exception? Thank you!

**Comment by kkarunakaran** [comment]
<img width="1588" alt="Screen Shot 2019-12-18 at 2 58 44 PM" src="https://user-images.githubusercontent.com/57362013/71118908-fc55f180-21a6-11ea-83c9-73c21b8f8d0c.png">

I just downloaded mopub-unity-warpper [from](https://github.com/mopub/mopub-unity-sdk/blob/master/unity-sample-app/Assets/MoPub/Plugins/Android/mopub-unity-wrappers.aar)

**Comment by SebaDudzic** [comment]
@chauduyphanvu 
`MoPub.IsInterstitialReady(placement.adUnitID)`

**Comment by chauduyphanvu** [comment]
@SebaDudzic, thanks for letting us know! We will address this in an upcoming SDK release.

**Comment by kkarunakaran** [comment]
Any update on this issue? Do you have an ETA of when the next release will be. Thanks

**Comment by chauduyphanvu** [comment]
@kkarunakaran, we've fixed this internally and will deploy it in an upcoming SDK release. There currently is no ETA yet. We'll update you once the SDK is released!

**Comment by aornelas** [comment]
Just verified that the just-released [5.11.0](https://github.com/mopub/mopub-unity-sdk/releases/tag/v5.11.0) has correctly addressed this issue. Thank you for your patience!
